[build]
  command = "./build-command.sh"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  PYTHON_VERSION = ""
  PYTHON_RUNTIME = ""
  RUNTIME = "nodejs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 